stages:
  - deploy

cache:
  paths:
  - vendor/

deploy_test:
  stage: deploy
  tags:
    - bumblebee
  only:
    - /^test\d+$/
  before_script:
    - export BRANCH_INDEX=$(echo ${CI_COMMIT_REF_SLUG} | grep -o "[1-9]")
    - export REDIS_BASE_DB=$(($((${BRANCH_INDEX}-1))*3))
    - export REDIS_CACHE_DB=$((${REDIS_BASE_DB}+200))
    - export REDIS_SESSION_DB=$((${REDIS_BASE_DB}+1+200))
    - export REDIS_FPC_DB=$((${REDIS_BASE_DB}+2+200))
  script:
    - sed -i -e "s/__SUBDOMAIN__/$SUBDOMAIN/g" deploy/test/etc/nginx/nginx.conf
    - envsubst < deploy/test/bin/config-provision.tpl.sh > deploy/test/bin/config-provision.sh
    - envsubst < deploy/test/bin/import-db.tpl.sh > deploy/test/bin/import-db.sh
    - envsubst < deploy/test/etc/magento/env.tpl2.php > app/etc/env.php
    - dep deploy:unlock test
    - dep deploy test
  variables:
    MYSQL_HOST: ${TEST_MYSQL_HOST}
    MYSQL_USER: ${TEST_MYSQL_USER}
    MYSQL_PASSWORD: ${TEST_MYSQL_PASSWORD}
    MYSQL_DATABASE: playground_${CI_COMMIT_REF_SLUG}
    ENC_KEY: ${TEST_ENC_KEY}
    APP_DESTINATION: ${TEST_APP_DESTINATION}/${CI_COMMIT_REF_SLUG}
    REDIS_HOST: ${TEST_REDIS_HOST}
    ELASTIC_HOST: ${TEST_ELASTIC_HOST}
    ELASTIC_PORT: ${TEST_ELASTIC_PORT}
    SUBDOMAIN: ${CI_COMMIT_REF_SLUG}