.common: &common
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  forwardAgent: true
  multiplexing: true
  become: "magento"
  port: 22

.test: &test
  user: builder
  identityFile: "~/.ssh/playground_deploy_test"
  stage: "test"


front-node-test:
  <<: *common
  <<: *test
  hostname: '94.130.177.101'
  roles: [ "front-node" ]